name: scraper

############
# SETTINGS #
############

log_level: 1                                  # LOG LEVELS: 1: [INFO] 2: [DEBUG] 3: [ERROR]
timeout: 1                                    # Timeout how long the scraper should wait before doing a new request
script_detector: true                         # Enable or disable the script_detector for the scraper
no_title_text: "Internal link - No title"     # What title do internal links get in the database






